export const SET_CUSTOMER = 'SET_CUSTOMER'

export const REQUEST_SETTINGS = 'REQUEST_SETTINGS'
export const RECEIVE_SETTINGS = 'RECEIVE_SETTINGS'

export const REQUEST_OFFER = 'REQUEST_OFFER'
export const RECEIVE_OFFER = 'RECEIVE_OFFER'
